create table customer_tbl 
( Cust_Id		integer 		
	GENERATED BY DEFAULT AS IDENTITY(
	START WITH 1, INCREMENT BY 1) 
	PRIMARY KEY,
Cust_Name		varchar(30)		not null,
Cust_address	varchar(20)		not null,
Cust_city		varchar(15)		not null,
Cust_State		varchar(2)		not null,
Cust_zip		numeric(5)		not null,
Cust_Phone		numeric(10),
Cust_Fax		numeric(10)
);
