INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES 
('LESLIE GLEASON','798 HARDAWAY DR','INDIANAPOLIS','IN',
47856,3175457690,NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Nancy Bunker','APT A 4556 WATERWAY','Broad Ripple','IN',
47950,3174262323,NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" )
VALUES
('Angela Dobko','RR3 Box 76','Lebanon','IN',
49967,7658970090,NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Wendy Wolf','3345 Gateway DR','INDIANAPOLIS','IN',
46224,3172913421,NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Marys Gift Shop','435 Main ST','DANVILLE','IL',
47978,3178567221,3178523434);

INSERT INTO CUSTOMER_TBL  
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Scottys Market', 'RR2 BOX 173', 'Brownsburg', 'IN',
45687, 3178529835, 3178529836);

INSERT INTO CUSTOMER_TBL  
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Jasons and Dallas Goodies', 'Lafayette SQ Mall', 'INDIANAPOLIS', 'IN',
46222, 3172978886, 3172978887);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Morgans Candies and Treats', '5657 W Tenth ST', 'INDIANAPOLIS', 'IN',
46234, 3172714398, NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Schylers Novelties', '17 Maple ST', 'Lebanon', 'IN',
48890, 3174346758, NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Gavings Place', '99801Rockville RD', 'INDIANAPOLIS', 'IN',
46244, 3172719991, 3172719992);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Hollis Gamearama', '567 US 31 South', 'Whiteland', 'IN',
49980, 3178879023, NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Heathers Feathers and Things', '4090 N Shadeland AVE', 'INDIANAPOLIS', 'IN',
43278, 317546768, NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" )
VALUES
('Ragans Hobies INC', '451 Green ST', 'Plainfield', 'IN',
46818, 3178393441, 3178399090);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Andys Candies', 'RR 1 Box 34', 'Nashville', 'IN',
48756, 8123239871, NULL);

INSERT INTO CUSTOMER_TBL 
( "CUST_NAME", "CUST_ADDRESS", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"CUST_PHONE", "CUST_FAX" ) 
VALUES
('Ryans Stuff', '2337 S Shelby ST', 'INDIANAPOLIS', 'IN',
47834, 3175634402, NULL);
